-- Incremental addition — run via phpMyAdmin (SQL tab). Do NOT re-run schema.sql.
-- Tracks which admin created/last-updated each item, shown in the CMS edit modals.

ALTER TABLE slides
  ADD COLUMN created_by INT UNSIGNED NULL AFTER subtitle,
  ADD COLUMN updated_by INT UNSIGNED NULL AFTER created_by,
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER updated_by,
  ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

ALTER TABLE projects
  ADD COLUMN created_by INT UNSIGNED NULL AFTER published,
  ADD COLUMN updated_by INT UNSIGNED NULL AFTER created_by,
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER updated_by,
  ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

ALTER TABLE team_members
  ADD COLUMN created_by INT UNSIGNED NULL AFTER img,
  ADD COLUMN updated_by INT UNSIGNED NULL AFTER created_by,
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER updated_by,
  ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

ALTER TABLE blog_posts
  ADD COLUMN created_by INT UNSIGNED NULL AFTER sort_order,
  ADD COLUMN updated_by INT UNSIGNED NULL AFTER created_by,
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER updated_by,
  ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;

ALTER TABLE collaborators
  ADD COLUMN created_by INT UNSIGNED NULL AFTER sort_order,
  ADD COLUMN updated_by INT UNSIGNED NULL AFTER created_by,
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER updated_by,
  ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at;
