-- Studio Dinding CMS schema + seed data
-- Import this once via phpMyAdmin (or `mysql -u USER -p DBNAME < schema.sql`) into the database
-- you created for this site. Seed values are copied 1:1 from the current hardcoded site content,
-- so importing this does not change anything visitors see on go-live.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ---------------------------------------------------------------------------
-- admin_users
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS admin_users;
CREATE TABLE admin_users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- No row is seeded here on purpose: a correct bcrypt hash has to be generated by PHP
-- itself (password_hash()), not hand-written into a SQL file. After importing this
-- schema and filling in shared/config.local.php, open
-- https://cms.studiodinding.id/api/setup.php once in the browser — it creates the
-- admin login (admin / studiodinding123) using a real hash, then delete
-- cms/api/setup.php from the server (it refuses to run again once a user exists,
-- but deleting it afterward is the safer habit).

-- ---------------------------------------------------------------------------
-- slides (Homepage hero carousel)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS slides;
CREATE TABLE slides (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  sort_order INT NOT NULL DEFAULT 0,
  img VARCHAR(255) NOT NULL,
  title_a VARCHAR(255) NOT NULL,
  title_b VARCHAR(255) NOT NULL,
  subtitle VARCHAR(500) NOT NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO slides (sort_order, img, title_a, title_b, subtitle) VALUES
  (0, 'assets/img/home-01.jpg', 'Every great design', 'begins here.', 'Timeless design, tailored to your lifestyle and vision.'),
  (1, 'assets/img/home-02.jpg', 'Quality over quantity,', 'seamless execution.', 'Full service from first concept to site supervision.'),
  (2, 'assets/img/home-03.jpg', 'Innovative architecture.', 'Timeless interiors.', 'Architecture and interiors that balance form, function and feeling.'),
  (3, 'assets/img/home-04.jpg', 'We don''t just design space —', 'we shape experiences.', 'From architecture to thoughtful interiors, we create environments that inspire.'),
  (4, 'assets/img/home-05.jpg', 'Every space', 'tells a story.', 'Let''s craft yours — architecture and interiors that reflect your identity.');

-- ---------------------------------------------------------------------------
-- project_categories (master data — replaces hardcoded residential/commercial)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS project_categories;
CREATE TABLE project_categories (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  slug VARCHAR(100) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO project_categories (id, name, slug, sort_order) VALUES
  (1, 'Residential', 'residential', 1),
  (2, 'Commercial', 'commercial', 2);

-- ---------------------------------------------------------------------------
-- projects (Portfolio) + project_gallery
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS project_gallery;
DROP TABLE IF EXISTS projects;

CREATE TABLE projects (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(64) NOT NULL,
  name VARCHAR(255) NOT NULL,
  type ENUM('residential','commercial') NOT NULL DEFAULT 'residential',
  category_id INT UNSIGNED NULL,
  location VARCHAR(255) NOT NULL DEFAULT 'Indonesia',
  services VARCHAR(255) NOT NULL DEFAULT 'Architecture & Interior Design',
  status VARCHAR(64) NOT NULL DEFAULT 'Completed',
  project_type_label VARCHAR(64) NOT NULL DEFAULT 'Private Residence',
  quote TEXT NOT NULL,
  seo_title VARCHAR(255) NULL,
  seo_description VARCHAR(300) NULL,
  cover_img VARCHAR(255) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  published TINYINT(1) NOT NULL DEFAULT 1,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE project_gallery (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  project_id INT UNSIGNED NOT NULL,
  img VARCHAR(255) NOT NULL,
  span VARCHAR(16) NOT NULL DEFAULT 'span 1',
  ratio VARCHAR(16) NOT NULL DEFAULT '4/5',
  sort_order INT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_project (project_id),
  CONSTRAINT fk_gallery_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO projects (slug, name, type, location, services, status, project_type_label, quote, cover_img, sort_order) VALUES
  ('ry-house', 'RY House', 'residential', 'Indonesia', 'Architecture & Interior Design', 'Completed', 'Private Residence', 'A family home built around calm, uncluttered volumes — natural materials and soft daylight carrying the design from room to room.', 'assets/img/ry-house-01.jpeg', 1),
  ('da-house', 'DA House', 'residential', 'Indonesia', 'Architecture & Interior Design', 'Completed', 'Private Residence', 'A composed family home where clean geometry and natural light take precedence over ornament — every room designed to age gracefully.', 'assets/img/da-house-01.jpg', 2),
  ('wo-residence', 'WO Residence', 'residential', 'Indonesia', 'Architecture & Interior Design', 'Completed', 'Private Residence', 'An open, breathing home planned around cross-ventilation and courtyard light, where indoor and outdoor spaces blur together.', 'assets/img/wo-residence-01.jpg', 3),
  ('ws-residence', 'WS Residence', 'residential', 'Jakarta, Indonesia', 'Architecture & Interior Design', 'Completed', 'Private Residence', 'A quiet, material-led home where architecture and interior were designed as one continuous language — light, texture and layout resolved together from the first sketch.', 'assets/img/ws-residence-01.jpg', 4),
  ('beauty-haul', 'Beauty Haul', 'commercial', 'Indonesia', 'Interior Design', 'Completed', 'Retail', 'A retail interior built to slow shoppers down — soft materials, warm lighting and clear sightlines guiding the experience end to end.', 'assets/img/beauty-haul-01.jpg', 5),
  ('villa-bag', 'Villa Bag', 'residential', 'Indonesia', 'Interior Design', 'Completed', 'Private Villa', 'A holiday retreat designed for slowness — warm textures, deep shade and interiors that open fully to the outdoors.', 'assets/img/villa-bag-01.jpg', 6),
  ('co-house', 'CO House', 'residential', 'Indonesia', 'Architecture & Interior Design', 'Completed', 'Private Residence', 'A concrete-and-timber home organized around a central courtyard, designed to stay cool and calm through every season.', 'assets/img/WO-HOUSE-01.jpg', 7),
  ('k-house', 'K House', 'residential', 'Indonesia', 'Architecture & Interior Design', 'Completed', 'Private Residence', 'A refined family residence where every material was chosen to age well — a home built to be lived in for generations.', 'assets/img/K-HOUSE-01.jpg', 8),
  ('hotel-milenium', 'Hotel Milenium', 'commercial', 'Indonesia', 'Interior Design & Renovation', 'Completed', 'Hospitality', 'A hospitality interior built for first impressions — refined finishes and a considered lighting scheme carried through every public space.', 'assets/img/hotel-milenium-01.jpg', 9),
  ('bsd-anggrek-loka', 'BSD Anggrek Loka', 'residential', 'BSD City, Tangerang', 'Architecture & Interior Design', 'Completed', 'Private Residence', 'A suburban home reworked around light and flow — open living spaces that step gently out toward the garden.', 'assets/img/bsd-anggrek-loka-01.jpg', 10),
  ('bs-residence', 'BS Residence', 'residential', 'Indonesia', 'Architecture & Interior Design', 'Completed', 'Private Residence', 'A considered renovation that keeps the home''s original character while resolving light, storage and flow for the way the family lives today.', 'assets/img/bs-residence-01.jpg', 11),
  ('cr-residence', 'CR Residence', 'residential', 'Indonesia', 'Architecture & Interior Design', 'Completed', 'Private Residence', 'A layered renovation that reveals the home in stages — each space more private than the last, ending in a quiet garden courtyard.', 'assets/img/cr-residence-01.jpg', 12);

UPDATE projects SET category_id = 1 WHERE type = 'residential';
UPDATE projects SET category_id = 2 WHERE type = 'commercial';

INSERT INTO project_gallery (project_id, img, span, ratio, sort_order) VALUES
  ((SELECT id FROM projects WHERE slug='ry-house'), 'assets/img/ry-house-02a.jpeg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='ry-house'), 'assets/img/ry-house-02b.jpeg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='ry-house'), 'assets/img/ry-house-03.jpeg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='ry-house'), 'assets/img/ry-house-04a.jpeg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='ry-house'), 'assets/img/ry-house-05.jpeg', 'span 1', '4/5', 5),
  ((SELECT id FROM projects WHERE slug='ry-house'), 'assets/img/ry-house-06.jpeg', 'span 2', '16/8', 6),

  ((SELECT id FROM projects WHERE slug='da-house'), 'assets/img/da-house-02.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='da-house'), 'assets/img/da-house-03.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='da-house'), 'assets/img/da-house-04a.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='da-house'), 'assets/img/da-house-05.jpg', 'span 2', '16/8', 4),

  ((SELECT id FROM projects WHERE slug='wo-residence'), 'assets/img/wo-residence-02a.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='wo-residence'), 'assets/img/wo-residence-04.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='wo-residence'), 'assets/img/wo-residence-06.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='wo-residence'), 'assets/img/wo-residence-08.jpg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='wo-residence'), 'assets/img/wo-residence-10.jpg', 'span 1', '4/5', 5),

  ((SELECT id FROM projects WHERE slug='ws-residence'), 'assets/img/ws-residence-02.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='ws-residence'), 'assets/img/ws-residence-04.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='ws-residence'), 'assets/img/ws-residence-06.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='ws-residence'), 'assets/img/ws-residence-08.jpg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='ws-residence'), 'assets/img/ws-residence-10.jpg', 'span 1', '4/5', 5),
  ((SELECT id FROM projects WHERE slug='ws-residence'), 'assets/img/ws-residence-12.jpg', 'span 2', '16/8', 6),
  ((SELECT id FROM projects WHERE slug='ws-residence'), 'assets/img/ws-residence-14.jpg', 'span 1', '4/5', 7),
  ((SELECT id FROM projects WHERE slug='ws-residence'), 'assets/img/ws-residence-16.jpg', 'span 1', '4/5', 8),

  ((SELECT id FROM projects WHERE slug='beauty-haul'), 'assets/img/beauty-haul-02.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='beauty-haul'), 'assets/img/beauty-haul-03.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='beauty-haul'), 'assets/img/beauty-haul-04.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='beauty-haul'), 'assets/img/beauty-haul-05.jpg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='beauty-haul'), 'assets/img/beauty-haul-06.jpg', 'span 1', '4/5', 5),

  ((SELECT id FROM projects WHERE slug='villa-bag'), 'assets/img/villa-bag-02.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='villa-bag'), 'assets/img/villa-bag-03.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='villa-bag'), 'assets/img/villa-bag-04.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='villa-bag'), 'assets/img/villa-bag-05.jpg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='villa-bag'), 'assets/img/villa-bag-06.jpg', 'span 1', '4/5', 5),

  ((SELECT id FROM projects WHERE slug='co-house'), 'assets/img/WO-HOUSE-02.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='co-house'), 'assets/img/WO-HOUSE-03.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='co-house'), 'assets/img/WO-HOUSE-04.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='co-house'), 'assets/img/WO-HOUSE-05.jpg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='co-house'), 'assets/img/WO-HOUSE-06.jpg', 'span 1', '4/5', 5),

  ((SELECT id FROM projects WHERE slug='k-house'), 'assets/img/K-HOUSE-02.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='k-house'), 'assets/img/K-HOUSE-03.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='k-house'), 'assets/img/K-HOUSE-04.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='k-house'), 'assets/img/K-HOUSE-05.jpg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='k-house'), 'assets/img/K-HOUSE-06.jpg', 'span 1', '4/5', 5),

  ((SELECT id FROM projects WHERE slug='hotel-milenium'), 'assets/img/hotel-milenium-02.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='hotel-milenium'), 'assets/img/hotel-milenium-03.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='hotel-milenium'), 'assets/img/hotel-milenium-04.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='hotel-milenium'), 'assets/img/hotel-milenium-05.jpg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='hotel-milenium'), 'assets/img/hotel-milenium-06.jpg', 'span 1', '4/5', 5),
  ((SELECT id FROM projects WHERE slug='hotel-milenium'), 'assets/img/hotel-milenium-07.jpg', 'span 2', '16/8', 6),

  ((SELECT id FROM projects WHERE slug='bsd-anggrek-loka'), 'assets/img/bsd-anggrek-loka-02.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='bsd-anggrek-loka'), 'assets/img/bsd-anggrek-loka-03.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='bsd-anggrek-loka'), 'assets/img/bsd-anggrek-loka-04.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='bsd-anggrek-loka'), 'assets/img/bsd-anggrek-loka-05.jpg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='bsd-anggrek-loka'), 'assets/img/bsd-anggrek-loka-06.jpg', 'span 1', '4/5', 5),
  ((SELECT id FROM projects WHERE slug='bsd-anggrek-loka'), 'assets/img/bsd-anggrek-loka-07.jpg', 'span 2', '16/8', 6),

  ((SELECT id FROM projects WHERE slug='bs-residence'), 'assets/img/bs-residence-02a.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='bs-residence'), 'assets/img/bs-residence-03a.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='bs-residence'), 'assets/img/bs-residence-04.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='bs-residence'), 'assets/img/bs-residence-05.jpg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='bs-residence'), 'assets/img/bs-residence-06a.jpg', 'span 1', '4/5', 5),
  ((SELECT id FROM projects WHERE slug='bs-residence'), 'assets/img/bs-residence-07.jpg', 'span 2', '16/8', 6),

  ((SELECT id FROM projects WHERE slug='cr-residence'), 'assets/img/cr-residence-02.jpg', 'span 1', '4/5', 1),
  ((SELECT id FROM projects WHERE slug='cr-residence'), 'assets/img/cr-residence-04.jpg', 'span 1', '4/5', 2),
  ((SELECT id FROM projects WHERE slug='cr-residence'), 'assets/img/cr-residence-05.jpg', 'span 2', '16/8', 3),
  ((SELECT id FROM projects WHERE slug='cr-residence'), 'assets/img/cr-residence-06.jpg', 'span 1', '4/5', 4),
  ((SELECT id FROM projects WHERE slug='cr-residence'), 'assets/img/cr-residence-08.jpg', 'span 1', '4/5', 5);

-- ---------------------------------------------------------------------------
-- team_members (About page)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS team_members;
CREATE TABLE team_members (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  sort_order INT NOT NULL DEFAULT 0,
  name VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  qualification VARCHAR(255) NOT NULL DEFAULT '',
  bio_p1 TEXT NOT NULL,
  bio_p2 TEXT NOT NULL,
  img VARCHAR(255) NOT NULL,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO team_members (sort_order, name, role, qualification, bio_p1, bio_p2, img) VALUES
  (1, 'Ryan Dharmansyah', 'PRINCIPAL & CHIEF ARCHITECT', 'B.Arch, M.Arch — University of New South Wales',
   'Born in Indonesia and raised in Sydney, Ryan trained as an architect across leading Australian practices before founding Studio Dinding, specializing in innovative, energy-conscious architecture.',
   'He believes the spaces we occupy shape how we behave — so every project is organized and optimized for genuine wellbeing, not just appearance.',
   'assets/img/people-1.jpg'),
  (2, 'Melita Lumanto', 'CREATIVE DIRECTOR', 'B.Des (Interior), M.Des (Lighting) — Swinburne / UTS Sydney',
   'Trained as an interior architect before specializing in lighting design, Melita brings a rare understanding of how light shapes form, materiality and mood in a space.',
   'Her work spans residential, hospitality and retail — including collaborations on projects in Singapore and Sydney — and she believes every good design begins with genuine listening.',
   'assets/img/people-2.jpg'),
  (3, 'Henry Chandra', 'CONSTRUCTION MANAGER', 'Bachelor of Civil Engineering — University of New South Wales',
   'Henry began his career as a junior quantity surveyor in Jakarta before rising to lead site teams across the studio''s projects.',
   'As Construction Manager, he oversees planning, budgeting and on-site execution — making sure every design is delivered exactly as drawn, on time.',
   'assets/img/people-3.jpg');

-- ---------------------------------------------------------------------------
-- contact_submissions (Contact form on the public site)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS contact_submissions;
CREATE TABLE contact_submissions (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  attachment VARCHAR(255) NULL,
  status ENUM('new','in_progress','closed') NOT NULL DEFAULT 'new',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- blog_posts
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS blog_posts;
CREATE TABLE blog_posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(150) NOT NULL,
  title VARCHAR(255) NOT NULL,
  excerpt VARCHAR(500) NOT NULL DEFAULT '',
  seo_title VARCHAR(255) NULL,
  seo_description VARCHAR(300) NULL,
  body MEDIUMTEXT NOT NULL,
  cover_img VARCHAR(255) NOT NULL DEFAULT '',
  published TINYINT(1) NOT NULL DEFAULT 1,
  published_at DATE NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_slug (slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- collaborators (partner/brand logos shown on the homepage)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS collaborators;
CREATE TABLE collaborators (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  name VARCHAR(150) NOT NULL,
  logo_img VARCHAR(255) NOT NULL,
  url VARCHAR(255) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_by INT UNSIGNED NULL,
  updated_by INT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ---------------------------------------------------------------------------
-- about_hero (About page hero headline/intro/photo — single row, id always 1)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS about_hero;
CREATE TABLE about_hero (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
  headline VARCHAR(255) NOT NULL DEFAULT '',
  intro_quote TEXT NOT NULL,
  img VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO about_hero (id, headline, intro_quote, img) VALUES
  (1,
   'The people behind every space we shape.',
   'A small, senior studio — architecture, interiors and construction working as one team, from first sketch to final handover.',
   'https://new.studiodinding.id/assets/img/about.jpg');

-- ---------------------------------------------------------------------------
-- contact_info (WhatsApp/email/address/Instagram — single row, id always 1)
-- ---------------------------------------------------------------------------
DROP TABLE IF EXISTS contact_info;
CREATE TABLE contact_info (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY DEFAULT 1,
  whatsapp VARCHAR(50) NOT NULL DEFAULT '',
  email VARCHAR(255) NOT NULL DEFAULT '',
  address VARCHAR(500) NOT NULL DEFAULT '',
  instagram_url VARCHAR(255) NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO contact_info (id, whatsapp, email, address, instagram_url) VALUES
  (1,
   '+62 812-8979-5996',
   'studiodinding@gmail.com',
   'Jl. Tanjung Duren Barat IV No.22A, Jakarta Barat 11470',
   'https://www.instagram.com/studio.dinding');

SET FOREIGN_KEY_CHECKS = 1;
